services:
  # Traefik reverse proxy
  traefik:
    build:
      context: .
      dockerfile: traefik/Dockerfile
    container_name: whatbeats-traefik
    ports:
      - "80:80"  # HTTP port
      - "443:443"  # HTTPS port (for SSL)
    depends_on:
      - frontend
      - backend
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - SSL_EMAIL=${SSL_EMAIL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker socket for dynamic configuration
      - traefik_certs:/etc/traefik/acme  # For storing SSL certificates
    restart: unless-stopped
    networks:
      - whatbeats-network

  # MongoDB database
  mongodb:
    image: mongo
    container_name: whatbeats-mongodb
    # No need to expose MongoDB port to host anymore
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - whatbeats-network

  # Backend API service
  backend:
    build:
      context: ..
      dockerfile: whatbeats/Dockerfile
      target: backend-stage
    container_name: whatbeats-backend
    # No need to expose backend port to host anymore
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=whatbeats
      - ENABLE_CORS=false  # CORS is handled by Traefik
      # Required environment variables - must be set in .env file or uncommented here
      # - JWT_SECRET_KEY=your_jwt_secret
      # - ADMIN_PASSWORD_HASH=your_admin_password_hash
      # - LLM_API_KEY=your_llm_api_key
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file from host
    restart: unless-stopped
    networks:
      - whatbeats-network
    command: ["python", "/app/backend/run.py"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      # SSL configuration (applied conditionally by traefik-entrypoint.sh)
      - "traefik.http.routers.backend-secure.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=letsencrypt"

  # Frontend service
  frontend:
    build:
      context: ..
      dockerfile: whatbeats/Dockerfile
      target: frontend-stage
    container_name: whatbeats-frontend
    # No need to expose frontend port to host anymore
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    environment:
      - DOMAIN=${DOMAIN:-localhost}  # Use DOMAIN env var for API URL
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file from host
    restart: unless-stopped
    networks:
      - whatbeats-network
    command: ["node", "/app/frontend/server.js"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      # SSL configuration (applied conditionally by traefik-entrypoint.sh)
      - "traefik.http.routers.frontend-secure.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"
      # HTTP to HTTPS redirect middleware (applied conditionally)
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

volumes:
  mongodb_data:
    name: whatbeats-mongodb-data
  traefik_certs:
    name: whatbeats-traefik-certs

networks:
  whatbeats-network:
    name: whatbeats-network
    driver: bridge

