services:
  # Traefik reverse proxy
  traefik:
    image: traefik:3.4
    container_name: whatbeats-traefik
    ports:
      - "80:80"  # HTTP port
      - "443:443"  # HTTPS port (for SSL)
    depends_on:
      - frontend
      - backend
    # Create necessary directories
    user: root
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - SSL_EMAIL=${SSL_EMAIL:-admin@example.com}
    entrypoint: >
      /bin/sh -c "
        mkdir -p /var/log/traefik /etc/traefik/acme &&
        touch /var/log/traefik/access.log &&
        chmod 600 /etc/traefik/acme/acme.json 2>/dev/null || true &&
        /entrypoint.sh"
    command:
      # API and dashboard configuration
      - "--api.insecure=false"
      - "--api.dashboard=true"
      # Entry points configuration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Providers configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=whatbeats-network"
      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Log configuration
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--accesslog.bufferingsize=100"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Docker socket for dynamic configuration
      - traefik_certs:/etc/traefik/acme  # For storing SSL certificates
    restart: unless-stopped
    networks:
      - whatbeats-network
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"
      # Global HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      # Security headers middleware
      - "traefik.http.middlewares.security-headers.headers.framedeny=true"
      - "traefik.http.middlewares.security-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.security-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.security-headers.headers.customframeoptionsvalue=SAMEORIGIN"
      - "traefik.http.middlewares.security-headers.headers.referrerpolicy=same-origin"

  # MongoDB database
  mongodb:
    image: mongo
    container_name: whatbeats-mongodb
    # No need to expose MongoDB port to host anymore
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - whatbeats-network

  # Backend API service
  backend:
    build:
      context: ..
      dockerfile: whatbeats/Dockerfile
      target: backend-stage
    container_name: whatbeats-backend
    # No need to expose backend port to host anymore
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=whatbeats
      - ENABLE_CORS=false  # CORS is handled by Traefik
      # Required environment variables - must be set in .env file or uncommented here
      # - JWT_SECRET_KEY=your_jwt_secret
      # - ADMIN_PASSWORD_HASH=your_admin_password_hash
      # - LLM_API_KEY=your_llm_api_key
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file from host
    restart: unless-stopped
    networks:
      - whatbeats-network
    command: ["python", "/app/backend/run.py"]
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend-service"
      # Apply middleware for HTTP to HTTPS redirect if SSL is enabled
      - "traefik.http.routers.backend.middlewares=redirect-to-https@docker"
      # HTTPS router
      - "traefik.http.routers.backend-secure.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.service=backend-service"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=letsencrypt"
      # Service definition
      - "traefik.http.services.backend-service.loadbalancer.server.port=8000"

  # Frontend service
  frontend:
    build:
      context: ..
      dockerfile: whatbeats/Dockerfile
      target: frontend-stage
    container_name: whatbeats-frontend
    # No need to expose frontend port to host anymore
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    environment:
      - DOMAIN=${DOMAIN:-localhost}  # Use DOMAIN env var for API URL
    volumes:
      - ./.env:/app/.env:ro  # Mount .env file from host
    restart: unless-stopped
    networks:
      - whatbeats-network
    command: ["node", "/app/frontend/server.js"]
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend-service"
      # Apply middleware for HTTP to HTTPS redirect if SSL is enabled
      - "traefik.http.routers.frontend.middlewares=redirect-to-https@docker"
      # HTTPS router
      - "traefik.http.routers.frontend-secure.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.service=frontend-service"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"
      # Service definition
      - "traefik.http.services.frontend-service.loadbalancer.server.port=3000"

volumes:
  mongodb_data:
    name: whatbeats-mongodb-data
  traefik_certs:
    name: whatbeats-traefik-certs

networks:
  whatbeats-network:
    name: whatbeats-network
    driver: bridge

