## Static configuration for Traefik

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  insecure: false
  dashboard: true

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Providers configuration
providers:
  # Docker provider
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "whatbeats-network"
  
  # File provider for dynamic configuration
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Let's Encrypt configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${SSL_EMAIL}"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

# Log configuration
log:
  level: "INFO"

# Access logs
accessLog:
  filePath: "/var/log/traefik/access.log"
  bufferingSize: 100

# Metrics configuration (optional)
metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0